/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_navclub_nes4j_app_audio_NativePlayer */

#ifndef _Included_cn_navclub_nes4j_app_audio_NativePlayer
#define _Included_cn_navclub_nes4j_app_audio_NativePlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_navclub_nes4j_app_audio_NativePlayer
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_navclub_nes4j_app_audio_NativePlayer_stop
  (JNIEnv *, jobject);

/*
 * Class:     cn_navclub_nes4j_app_audio_NativePlayer
 * Method:    play
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_cn_navclub_nes4j_app_audio_NativePlayer_play
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     cn_navclub_nes4j_app_audio_NativePlayer
 * Method:    config
 * Signature: (Ljava/lang/String;III)V
 */
JNIEXPORT void JNICALL Java_cn_navclub_nes4j_app_audio_NativePlayer_config
  (JNIEnv *, jobject, jstring, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
